### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by bjdavidson** [docwhat/docker-gc#6]
Jan 04 06:57:46 pickle01 docker-gc[2660]: fatal error: concurrent map read and map write
Jan 04 06:57:46 pickle01 docker-gc[2660]: goroutine 3943 [running]:
Jan 04 06:57:46 pickle01 docker-gc[2660]: runtime.throw(0x7d8793, 0x21)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:566 +0x95 fp=0xc420037e00 sp=0xc420037de0
Jan 04 06:57:46 pickle01 docker-gc[2660]: runtime.mapaccess2_faststr(0x762240, 0xc420053f80, 0xc420124cf0, 0xb, 0x2, 0x3e)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc420037e60 sp=0xc420037e00
Jan 04 06:57:46 pickle01 docker-gc[2660]: main.(*MemRecorder).SawImageTagAt(0xc4200e42e0, 0xc420124cf0, 0xb, 0xecffeda3a, 0x1543cd7c, 0x997b60)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/gopath/src/github.com/docwhat/docker-gc/memrecorder.go:25 +0x55 fp=0xc420037ed0 sp=0xc420037e60
Jan 04 06:57:46 pickle01 docker-gc[2660]: main.app.listenForEvents.func1(0xc420124cf0, 0xb, 0xecffeda3a, 0xc41543cd7c, 0x997b60)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/gopath/src/github.com/docwhat/docker-gc/main.go:97 +0x1d4 fp=0xc420037f88 sp=0xc420037ed0
Jan 04 06:57:46 pickle01 docker-gc[2660]: runtime.goexit()
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420037f90 sp=0xc420037f88
Jan 04 06:57:46 pickle01 docker-gc[2660]: created by main.(*Docker).HandleImageNameEvents
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/gopath/src/github.com/docwhat/docker-gc/docker.go:176 +0x1e4
Jan 04 06:57:46 pickle01 docker-gc[2660]: goroutine 1 [select (no cases), 139 minutes]:
Jan 04 06:57:46 pickle01 docker-gc[2660]: main.main()
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/gopath/src/github.com/docwhat/docker-gc/main.go:33 +0x442
Jan 04 06:57:46 pickle01 docker-gc[2660]: goroutine 34 [sleep, 7 minutes]:
Jan 04 06:57:46 pickle01 docker-gc[2660]: time.Sleep(0xd18c2e2800)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/time.go:59 +0xe1
Jan 04 06:57:46 pickle01 docker-gc[2660]: main.app.deleteOldImagesLoop(0xebbdb3ed0000, 0xd18c2e2800, 0x1a3185c5000, 0x0, 0x7d1329, 0x10, 0xc42000b300, 0x979d60, 0xc4200e42e0, 0xebbdb3ed0000, ...)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/gopath/src/github.com/docwhat/docker-gc/main.go:88 +0x40
Jan 04 06:57:46 pickle01 docker-gc[2660]: created by main.main
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/gopath/src/github.com/docwhat/docker-gc/main.go:29 +0x3f5
Jan 04 06:57:46 pickle01 docker-gc[2660]: goroutine 20 [IO wait]:
Jan 04 06:57:46 pickle01 docker-gc[2660]: net.runtime_pollWait(0x7fbfeafaef80, 0x72, 0x3)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/netpoll.go:160 +0x59
Jan 04 06:57:46 pickle01 docker-gc[2660]: net.(*pollDesc).wait(0xc42015e610, 0x72, 0xc4203d7aa0, 0xc42000e120)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/fd_poll_runtime.go:73 +0x38
Jan 04 06:57:46 pickle01 docker-gc[2660]: net.(*pollDesc).waitRead(0xc42015e610, 0x9769a0, 0xc42000e120)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/fd_poll_runtime.go:78 +0x34
Jan 04 06:57:46 pickle01 docker-gc[2660]: net.(*netFD).Read(0xc42015e5b0, 0xc420167000, 0x1000, 0x1000, 0x0, 0x9769a0, 0xc42000e120)
Jan 04 06:57:46 pickle01 docker-gc[2660]: /home/travis/.gimme/versions/go1.7.linux.amd64/src/net/fd_unix.go:243 +0x1a1

**Comment by docwhat** [comment]
So reading, I found [this stackoverflow](http://stackoverflow.com/questions/11063473/map-with-concurrent-access) that says:

> In Go, maps are not thread-safe. Also, data requires locking even for reading if, for example, there could be another goroutine that is writing the same data (concurrently, that is).
